### ISSUE TITLE
English version of README 

### ISSUE THREAD

**Issue by inuyasha82** [inuyasha82/DreamOs#12]
Translate the readme file in english.

**Comment by Emily82** [comment]
I translated README document, when you have time, check for it ;)

[README-en.md.zip](https://github.com/inuyasha82/DreamOs/files/670149/README-en.md.zip)

**Comment by Emily82** [comment]
Here, i fixed "Operative system" to "Operating system"

[README-en.md.zip](https://github.com/inuyasha82/DreamOs/files/697197/README-en.md.zip)
