### ISSUE TITLE
Dreamos getting stuck on x86 64bit real hardware pc

### ISSUE THREAD

**Issue by Emily82** [inuyasha82/DreamOs#27]
I tested dreamos on AMD K8 64bit and it stops after "Paging" label.
Interrupts are not disabled, keyboard works,  simply OS does not go ahead.

This issue does NOT occur on real x86 32bit platform and on emulators (both 32bit and 64bit)

**Comment by amanuel2** [comment]
This os has Amd64 support?!

**Comment by Emily82** [comment]
No, but for compatibility Amd64 should run 32bit os.

**Comment by amanuel2** [comment]
Then if Amd64 is backward compatible how does it not run this os?

**Comment by Emily82** [comment]
Maybe there is something very little different about paging, retro-compatibility does not mean fully identical. We will work on this.
If you want a real example, you can install without problems linux 32bit on Amd64 platform, even if it will read only 3GB ram, without PAE support enabled.

**Comment by amanuel2** [comment]
Ok. I thought u meant fully compatible, my bad

**Comment by Emily82** [comment]
Commit cdfa093aedc5f494782073b971c903d31f8c8e0b fixed this issue.
