### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by inuyasha82** [inuyasha82/DreamOs#3]
During login there are 2 problems:
1. If you press backspace it will erase also the login message.
2. Sometimes if you type the user name correctly it doesn't let you in.

**Comment by Emily82** [comment]
I can't reproduce this bug in Bochs. I press the backspace and the login message isn't deleted.

**Comment by Emily82** [comment]
In commit 03c3238174762865d71744d99d17e0a156e115bb i fixed this issue.
