### ISSUE TITLE
If a wrong username is inserted, then user cannot login

### ISSUE THREAD

**Issue by inuyasha82** [inuyasha82/DreamOs#5]
If a wrong username is typed, then user cannot login even if the correct username is inserted.

**Comment by Emily82** [comment]
I fixed the bug in my local copy. In shell function in shell.c all memset initializations should be inside do-while block to reset the username for every cycle-check.

**Comment by Emily82** [comment]
In commit 03c3238174762865d71744d99d17e0a156e115bb the issue should be already fixed.
