### ISSUE TITLE
Bootable floppy for DreamOs64

### ISSUE THREAD

**Issue by informer2016** [inuyasha82/DreamOs#56]
Following #54 , I'm opening this issue. If you could make such a floppy, I will be happy to test it as a part of laptop's coreboot BIOS

**Comment by dreamos82** [comment]
maybe you wanted to open it here https://github.com/dreamos82/DreamOs64/ ?

**Comment by informer2016** [comment]
@dreamos82 True! I'll close this topic and open a similar one at this repo.
